### ISSUE TITLE
Questions about CZT for RS algorithm 

### ISSUE THREAD

**Issue by sihan-shao** [artificial-scientist-lab/XLuminA#2]
Hi, 

Thank you for your interesting work! I have a few questions about the code for the CZT in the RS algorithm. I don't understand why the CZT can be directly applied to the RS algorithm, as only Fresnel diffraction is derived by Eq. 6 in the reference paper.

Additionally, the formula for computing f1 and f2 in S15 and S16 of the Supplementary Material, ,also found in the source code:

```  # Intermediate frequency
    D1 = f1 + (M_out * Dm + f2 - f1) / (2 * M_out) 
    # Upper frequency limit
    D2 = f2 + (M_out * Dm + f2 - f1) / (2 * M_out) 
```
is confusing to me because I couldn't find any derivation in the reference paper. I would appreciate it if you could provide additional materials or answer my questions.

Thank you very much.

**Comment by CarlaRodriguez96** [comment]
Hi, 

thank you for your interest! I'm happy to explain how we incorporate the Chirped Z-Transform (CZT) in [wave_optics.py](https://github.com/artificial-scientist-lab/XLuminA/blob/main/xlumina/wave_optics.py) (this approach can be easily extended to [vectorial_optics.py](https://github.com/artificial-scientist-lab/XLuminA/blob/main/xlumina/vectorized_optics.py) using `jax.vmap`):

1. In the `RS_propagation` method, we use `build_grid`, followed by `RS_propagation_jit` (which calls `transfer_function_RS`), and then compute the function `U`.

2. The `CZT` function follows a similar structure, but with key differences:

- It uses `build_CZT_grid` (which is different from the `build_grid` used in `RS_propagation`)
- `CZT_jit` is called, which uses `transfer_function_RS` for both F and F0.
- It computes U using the `Bluestein_method`.

The `Bluestein_method` is adapted from MATLAB code provided by [yanleihu](https://github.com/yanleihu/Bluestein-Method) (the same source mentioned by the authors you referenced). The formulas you noted from the supplementary material are implemented within this method.

Importantly, both approaches use `transfer_function_RS`, which is the Rayleigh-Sommerfeld (RS) optical propagator, not the Fresnel approximation. Note that we compute the exact distance: `r = jnp.sqrt(Xext ** 2 + Yext ** 2 + z ** 2)`. Also, it's worth mentioning that the Bluestein method is a computational technique for efficient DFT calculation and is not limited to Fresnel approximations. This allows its application in various scenarios.

I hope this clarifies your question. If you need any further information, please don't hesitate to email me.

Thank you for using XLuminA :) !
